// frontend/appflowy_tauri/src/App.svelte
<script lang="ts">
  import Greet from './lib/Greet.svelte'
</script>

<main class="container">
  <h1>Welcome to Tauri!</h1>

  <div class="row">
    <a href="https://vitejs.dev" target="_blank">
      <img src="/vite.svg" class="logo vite" alt="Vite Logo" />
    </a>
    <a href="https://tauri.app" target="_blank">
      <img src="/tauri.svg" class="logo tauri" alt="Tauri Logo" />
    </a>
    <a href="https://svelte.dev" target="_blank">
      <img src="/svelte.svg" class="logo svelte" alt="Svelte Logo" />
    </a>
  </div>

  <p>
    Click on the Tauri, Vite, and Svelte logos to learn more.
  </p>

  <div class="row">
    <Greet />
  </div>


</main>

<style>
  .logo.vite:hover {
    filter: drop-shadow(0 0 2em #747bff);
  }

  .logo.svelte:hover {
    filter: drop-shadow(0 0 2em #ff3e00);
  }
</style>

// frontend/appflowy_tauri/src/App.jsx
import { useState } from "react";
import reactLogo from "./assets/react.svg";
import { invoke } from "@tauri-apps/api/tauri";
import { emit, listen } from "@tauri-apps/api/event";
import { Button } from 'antd';

import "./App.css";

const AF_EVENT = "af-event";
const AF_NOTIFICATION= "af-notification";
async function emit_af_event(payload) {
    // listen(AF_NOTIFICATION, (event) => {
    //     // event.event is the event name (useful if you want to use a single callback fn for multiple event types)
    //     // event.payload is the payload object
    //     console.log(event);
    // });
    emit(AF_EVENT, payload)
}


function App() {
    async function invokeCommand() {
        let args = {
            request: {
                ty: "InitUser",
                payload: 'hello'
            }
        };
        let response = await invoke("invoke_request",  args );
        console.log(response);
    }

    return (
        <div className="container">
            <h1>Welcome to Tauri!</h1>

            <div className="row">
                <a href="https://vitejs.dev" target="_blank">
                    <img src="/vite.svg" className="logo vite" alt="Vite logo" />
                </a>
                <a href="https://tauri.app" target="_blank">
                    <img src="/tauri.svg" className="logo tauri" alt="Tauri logo" />
                </a>
                <a href="https://reactjs.org" target="_blank">
                    <img src={reactLogo} className="logo react" alt="React logo" />
                </a>
            </div>

            <p>Click on the Tauri, Vite, and React logos to learn more.</p>

            <Button type="primary" onClick={() => invokeCommand()}>Button</Button>
        </div>
    );
}

export default App;
